name: C Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up build tools
      run: sudo apt-get install build-essential
    - name: Build
      run: make
    - name: Run
      run: ./main
